// ........................
// ...9 starts with here...
// ........................

// var num1 = 10;
// var num2 = 3;
// var num3 = num1 + num2;
// console.log(num3);
// var num3 = num1 - num2;
// console.log(num3);
// var num3 = num1 * num2;
// console.log(num3);
// var num3 = num1 / num2;
// console.log(num3);
// var num3 = num1 % num2;
// console.log(num3);
// ........................
// ...9 ends with here...
// ........................

// ........................
// ...10 starts with here...
// ........................
// var num1 = 10;
// num1 += 1;
// console.log(num1);
// var num1 = 10;
// num1 -= 1;
// console.log(num1);
// var num1 = 10;
// num1 *= 2;
// console.log(num1);
// var num1 = 10;
// num1 *= 2;
// console.log(num1);
// ........................
// ...10 ends with here...
// ........................

// ........................
// ...11 starts with here...
// ........................
// var num1 = 10;
// num1++;
// console.log(num1);
// var num1 = 10;
// num1--;
// console.log(num1);
// ........................
// ...11 ends with here...
// ........................

// ........................
// ...12 starts with here...
// ........................
// var num1 = 12.594674;
// var num2 = 10;
// var sum = num1 + num2;
// sum = parseInt(sum);
// console.log(sum);

// support........................................................
// var num = "12.4";
// var num2 = parseFloat(num);
// console.log(num + 1);
// console.log(num2 + 1);

// var num1 = 12.594674;
// var num2 = 10;
// var sum = num1 + num2;
// sum = sum.toFixed(3);
// console.log(sum);
// ........................
// ...12 ends with here...
// ........................

// ........................
// ...13 starts with here...
// ........................
// var fruits = ["apple", "orange", "mango"];
// console.log(fruits);
// ........................
// ...13 ends with here...
// ........................

// ........................
// ...14 starts with here...
// ........................
// var names = ["proma", "mukta", "oyeishi"];
// console.log(names.length);
// ........................
// ...14 ends with here...
// ........................

// ........................
// ...15 starts with here...
// ........................
// var names = ["proma", "mukta", "oyeishi"];
// var name = names.indexOf("proma");
// console.log(name);
// var names = ["proma", "mukta", "oyeishi"];
// names[2] = "sajid";
// console.log(names);
// ........................
// ...15 ends with here...
// ........................

// ........................
// ...16 starts with here...
// ........................

// ........................
// ...16 ends with here...
// ........................

// ........................
// ...17 starts with here...
// ........................
// var names = ["proma", "mukta", "sajid", "sudipto"];
// var element = names[1];
// console.log(element);
// ........................
// ...17 ends with here...
// ........................

// ........................
// ...18 starts with here...
// ........................
// var names = ["Neel", "Jagannath", "Diviya", "Mukta"];
// names[3] = "Proma";
// console.log(names);
// ........................
// ...18 ends with here...
// ........................
// ........................

// ...19 starts with here...
// ........................
// var names = ["Neel", "Jagannath", "Diviya", "Mukta"];
// var name = names.indexOf("Diviya");
// console.log(name);
// ........................
// ...19 ends with here...
// ........................

// ...20 starts with here...
// ........................

// ........................
// ...20 ends with here....

// ........................
// ...21 starts with here...
// ........................
// var players = ["Sakib", "Mashrafi", "Musfiq", "Mahmuddullah"];
// players.push("Tamim");
// console.log(players);

// var players = ["Sakib", "Mashrafi", "Musfiq", "Mahmuddullah", "Tamim", "jamim"];
// players.pop();
// console.log(players);
// ........................
// ...21 ends with here...
// ........................

// ........................
// ...22 starts with here...
// ........................
// var friends = ["Proma", "Mukta", "Oyeishi"];
// friends.shift();
// console.log(friends);

// var friends = ["Proma", "Mukta", "Oyeishi"];
// friends.unshift("Sajid");
// console.log(friends);
// ........................
// ...22 ends with here...
// ........................

// ........................
// ...23 starts with here...
// ........................

// ........................
// ...23 ends with here...
// ........................

// ........................
// ...24 starts with here...
// ........................
// var money = 500;
// if (money >= 80000) {
//   console.log("I will Buy Mac");
// } else if (money >= 60000) {
//   console.log("I will Buy Gaming leptop");
// } else if (money >= 40000) {
//   console.log("I will Buy Lenovo Yoga");
// } else if (money >= 20000) {
//   console.log("I will Buy Used Leptop");
// } else {
//   console.log("I will work by Mobile");
// }
// ........................
// ...24 ends with here...
// ........................

// ........................
// ...25 starts with here...
// ........................
// for (var i = 1; i < 40; i++) {
//   console.log("আসকে আমার মন ভালো নেই");
// }
// ........................
// ...25 ends with here...
// ........................

// ........................
// ...29 starts with here...
// ........................
// for (var i = 58; i < 99; i++) {
//   console.log(i);
// }
// ........................
// ...29 ends with here...
// ........................

// ........................
// ...30 starts with here...
// ........................
// for (var i = 412; i <= 456; i += 2) {
//   console.log(i);
// }
// ........................
// ...30 ends with here...
// ........................

// ........................
// ...31 starts with here...
// ........................
// for (var i = 581; i <= 623; i += 2) {
//   console.log(i);
// }
// ........................
// ...31 ends with here...
// ........................

// ........................
// ...33 starts with here...
// ........................
// var names = [
//   "HTMl",
//   "CSS",
//   "Responsive Design",
//   "Bootstrap",
//   "Tailwind",
//   "Basic JS",
// ];

// for (var i = 0; i < names.length; i++) {
//   console.log(names[i]);
// }
// ........................
// ...33 ends with here...
// ........................

// ........................
// ...34 starts with here...
// ........................
// var mobileNames = ["nokia", "Samgsang", "Shaomi", "Samphoni"];
// var mobileIndex = 0;
// while (mobileIndex < mobileNames.length) {
//   console.log(mobileNames[mobileIndex]);
//   mobileIndex++;
// }
// ........................
// ...34 ends with here...
// ........................

// ........................
// ...35 starts with here...
// ........................
// for (var i = 30; i <= 86; i++) {
//   console.log(i);
//   if (i == 44) {
//     break;
//   }
// }
// ........................
// ...35 ends with here...
// ........................

// ........................
// ...36 starts with here...
// ........................
// var bookPrice = [50, 100, 200, 300, 400, 500];
// for (var i = 0; i <= bookPrice.length; i++) {
//   console.log(i);
//   if (i == 44) {
//     continue;
//   }
// }
// ........................
// ...36 ends with here...
// ........................
